### ISSUE TITLE
更新主题后无法正常打开文章

### ISSUE THREAD

**Issue by MRLEEBLO** [Cerallin/hexo-theme-yuzu#10]
在博客内表现为标签页一直打转，打不开文章。
git报错如图：
![uTools_1688266552852](https://github.com/Cerallin/hexo-theme-yuzu/assets/137767483/7bd4983e-2423-4895-8405-dbf8e965078b)

**Comment by Cerallin** [comment]
请切换到v2.x分支试试，当前master分支做了较大修改：使用pug替代EJS作为renderer。迁移方法参见readme

付切换分支的指令
```shell
git checkout v2.x
```

**Comment by Qinch** [comment]
> 你好，我这里切到2.x分支，也是报错,
@Cerallin 麻烦帮忙看下

<img width="759" alt="image" src="https://github.com/Cerallin/hexo-theme-yuzu/assets/5291693/27aa6215-df65-4208-8b1e-ab7f95e47d5b">

**Comment by Cerallin** [comment]
@Qinch 你的`_config.yml`里缺少一些配置：
```yaml
visit_count:
  type: busuanzi
  # or
  # type: visitor-counter
  # url: //your.counter.site/count.php
```
这部分内容，master分支的readme也是适用的，请复制相应代码到你的hexo根目录下的`_config.yml`里，然后根据自己的需求修改
